### ISSUE TITLE
How to configure Apache Shiro bundles correctly for use in Apache Karaf

### ISSUE THREAD

**Issue by craigalansmith** [apache/shiro#1333] opened 2024-03-01 08:33 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Question

Hi,
Any help or advice on this issue would be greatly appreciated!

I am trying to use Apache Shiro v1.13.0 with Karaf. I have used it successfully with an older version of Shiro which had fewer modules (and therefore fewer karaf bundles).
When I use version 1.13.0 I get the following error when the Karaf container starts up:
`java.lang.ClassNotFoundException: org.apache.shiro.config.IniSecurityManagerFactory not found by org.apache.shiro.config.core`

It seems to me that the problem here is that Karaf is trying to load a class from the wrong bundle - the class is actually in org.apache.shiro.config. But the fact that the org.apache.shiro.config package is exported from both bundles seems to be confusing it.
I think this needs to be addressed on the maven side in the configuration of the bundles. What would a standard configuration look like?
I don't see anything in the docs describing how to get this set up so any help would be much appreciated.
Regards,
CS

**Comment by fpapon** [comment] 2024-03-01 09:00
The feature has been fixed on latest Shiro 2.0.0 version, can you try with this version?

**Comment by craigalansmith** [comment] 2024-03-01 09:39
Thanks for responding so quickly!

Unfortunately I am using Java 8 so I don’t think I can use Shiro 2.0?

**Comment by lprimak** [comment] 2024-03-01 16:11
Duplicate of #1300 
I do not believe this can be fixed without breaking compatibility. This is why this is fixed in 2.0 and not in 1.x

**Closed by lprimak** 2024-03-01 16:11 UTC
Labels: question
