### ISSUE TITLE
[Feature] ShiroFilterFactoryBean with Jakarta Filter compatibility

### ISSUE THREAD

**Issue by pascencio** [apache/shiro#1428] opened 2024-04-20 01:48 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/shiro/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

I'm using apache shiro with spring boot integration and Jakarta EE. All dependencies use Jakarta classifier:
```xml
<dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-core</artifactId>
            <classifier>jakarta</classifier>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-web</artifactId>
            <classifier>jakarta</classifier>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-spring-boot-web-starter</artifactId>
            <classifier>jakarta</classifier>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-spring-boot-starter</artifactId>
            <classifier>jakarta</classifier>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-spring</artifactId>
            <classifier>jakarta</classifier>
            <version>2.0.0</version>
        </dependency>
```

When I try to create my ShiroFilterFactoryBean have a trouble with the method setFilters that expect a javax.servlet.Filter type.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lprimak** [comment] 2024-04-20 02:07
Duplicate of #1346 


See https://shiro.apache.org/jakarta-ee.html section and include `shiro-bom` as directed there.

**Closed by lprimak** 2024-04-20 02:07 UTC

**Comment by lprimak** [comment] 2024-04-20 20:57
Just to clarify, this is needed:
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-bom</artifactId>
            <version>2.0.0</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by pascencio** [comment] 2024-04-21 00:16
> Just to clarify, this is needed:
> 
> ```
> <dependencyManagement>
>     <dependencies>
>         <dependency>
>             <groupId>org.apache.shiro</groupId>
>             <artifactId>shiro-bom</artifactId>
>             <version>2.0.0</version>
>             <scope>import</scope>
>             <type>pom</type>
>         </dependency>
>     </dependencies>
> </dependencyManagement>
> ```

Thanks. I saw the example, and those tags are not in my pom.xml.

**Comment by lprimak** [comment] 2024-04-21 00:57
Yes
